# Generated by Django 3.2.6 on 2021-08-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='graph',
            field=models.ImageField(blank=True, null=True, upload_to='graphs/', verbose_name='График'),
        ),
    ]
